### ISSUE TITLE
getDNN() error , model created successfully , but tensorflow is generating error

### ISSUE THREAD

**Issue by matesio** [hyung8758/HY_python_NN#1]
Traceback (most recent call last):
  File "train.py", line 111, in <module>
    dnn.genDNN()
  File "/home/hammad/Desktop/ArtificialIntelligenceTerminal/esnet_python/main/dnnnetworkmodels.py", line 73, in genDNN
    self.last_out = tf.matmul(outputActivation[-1],self.weightMatrix[-1]) + self.biasMatrix[-1]
  File "/home/hammad/.local/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py", line 1749, in matmul
    with ops.name_scope(name, "MatMul", [a, b]) as name:
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/hammad/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 4167, in name_scope
    g = _get_graph_from_inputs(values)
  File "/home/hammad/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3912, in _get_graph_from_inputs
    _assert_same_graph(original_graph_element, graph_element)
  File "/home/hammad/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3851, in _assert_same_graph
    "%s must be from the same graph as %s." % (item, original_item))
ValueError: Tensor("Cast_1:0", shape=(100, 10), dtype=float32) must be from the same graph as Tensor("Sigmoid:0", shape=(?, 100), dtype=float32).

**Comment by hyung8758** [comment]
Oh Thanks for your reports. I should've posted the issue that you are experiencing on the README but I didn't. The error you mentioned is expected because I didn't fixed the DNN problem when it gets the parameters(weights and biases) from RBM training. If you run the DNN solely(which means you are not importing weights and biases from RBM training ), then you will see that the training is going smoothly.
